#!/usr/bin/env node
/**
 * The colour tokens, solved rather than picked.
 *
 * The original palette had a lightness spread of 0.36 in OKLCH, so five of its
 * seven colours could not carry text on white and two of them were the same
 * colour as each other (docs/decisions.md D7). Fixing that by eye means
 * fiddling until it looks right and finding out later that it is 4.2:1. So each
 * step is solved: a hue and a role go in, the lightest lightness that still
 * clears the contrast floor comes out, at the most chroma the sRGB gamut holds.
 *
 *   node tools/tokens.mjs        writes brand/tokens/color.json
 */
import { writeFileSync } from 'node:fs';

const WHITE = '#ffffff';
const NAVY = '#101554';
const PINK = '#ef2f88';
const TEXT = 4.5;

const toLin = (c) => (c / 255 <= 0.04045 ? c / 255 / 12.92 : ((c / 255 + 0.055) / 1.055) ** 2.4);
const toSrgb = (c) => {
  const v = Math.min(1, Math.max(0, c));
  return v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055;
};

function oklchToRgb(L, C, H) {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

function rgbToOklch(hex) {
  const h = hex.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => toLin(parseInt(h.slice(i, i + 2), 16)));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return [L, Math.hypot(A, B), ((Math.atan2(B, A) * 180) / Math.PI + 360) % 360];
}

const inGamut = (L, C, H) => oklchToRgb(L, C, H).every((v) => v >= -1e-4 && v <= 1 + 1e-4);

/** The most chroma this lightness and hue can hold in sRGB. */
function maxChroma(L, H) {
  let lo = 0;
  let hi = 0.45;
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2;
    if (inGamut(L, mid, H)) lo = mid;
    else hi = mid;
  }
  return lo;
}

const hex = (L, C, H) =>
  '#' +
  oklchToRgb(L, Math.min(C, maxChroma(L, H)), H)
    .map((v) => Math.round(toSrgb(v) * 255).toString(16).padStart(2, '0'))
    .join('');

const luminance = (h) => {
  const s = h.replace('#', '');
  return 0.2126 * toLin(parseInt(s.slice(0, 2), 16)) + 0.7152 * toLin(parseInt(s.slice(2, 4), 16)) + 0.0722 * toLin(parseInt(s.slice(4, 6), 16));
};
const contrast = (a, b) => {
  const [x, y] = [luminance(a), luminance(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
};

/** The lightest step of this hue that still clears `target` against `against`. */
function lightestPassing(H, C, against, target = TEXT) {
  let best = null;
  for (let L = 0.3; L <= 0.9; L += 0.0025) {
    const h = hex(L, C, H);
    if (contrast(h, against) >= target) best = h;
  }
  if (!best) throw new Error(`no step of hue ${H} clears ${target}:1 against ${against}`);
  return best;
}

const tok = ($value, $description) => ({ $value, $description });

const [, pinkC, pinkH] = rgbToOklch(PINK);
const [, , navyH] = rgbToOklch(NAVY);

/** Hues kept from the original palette, less #ff005c, plus a red that is not the brand pink. */
const ACCENTS = { orange: 40.6, amber: 85, green: 161.7, teal: 215, blue: 273.9, purple: 310, red: 25 };

const NEUTRALS = [
  ['50', 0.985, 0.004], ['100', 0.96, 0.006], ['200', 0.91, 0.008], ['300', 0.84, 0.01],
  ['400', 0.72, 0.014], ['500', 0.62, 0.018], ['600', 0.52, 0.022], ['700', 0.42, 0.026],
  ['800', 0.32, 0.032], ['900', 0.23, 0.045], ['950', 0.17, 0.055],
];

const out = {
  $description:
    'WavingEye brand colour. Generated by tools/tokens.mjs; edit the generator, not this file.',
  color: { $type: 'color', brand: {}, neutral: {}, accent: {}, semantic: {} },
};

out.color.brand = {
  pink: tok(PINK, 'Identity. The mark, never altered. 3.87:1 on white, graphics only.'),
  pinkOnLight: tok(lightestPassing(pinkH, pinkC, WHITE), 'Pink for text and UI on white or neutral-50. >=4.5:1.'),
  pinkOnDark: tok(hex(0.72, pinkC, pinkH), 'Pink for text and UI on navy or neutral-900. >=4.5:1.'),
  navy: tok(NAVY, 'Identity dark. Default logo colour on light surfaces. 16.7:1 on white.'),
  white: tok(WHITE, 'Logo colour on brand and dark surfaces.'),
  black: tok('#000000', 'One-colour reproduction only: fax, embossing, single-plate print.'),
};

for (const [name, L, C] of NEUTRALS)
  out.color.neutral[name] = tok(hex(L, C, navyH), `L*=${L.toFixed(3)} on the navy hue.`);

for (const [name, H] of Object.entries(ACCENTS)) {
  const display = maxChroma(0.65, H) * 0.95;
  out.color.accent[name] = {
    400: tok(hex(0.8, maxChroma(0.8, H) * 0.9, H), 'On navy and neutral-900.'),
    500: tok(hex(0.65, display, H), 'Display and fills.'),
    600: tok(lightestPassing(H, display, WHITE), 'Text and UI on white.'),
  };
}

out.color.semantic = {
  success: tok('{color.accent.green.600}', 'Never a brand colour: a UI must not say "this failed" in pink.'),
  warning: tok('{color.accent.amber.600}', ''),
  danger: tok('{color.accent.red.600}', ''),
  info: tok('{color.accent.blue.600}', ''),
};

const path = new URL('../brand/tokens/color.json', import.meta.url);
writeFileSync(path, JSON.stringify(out, null, 2) + '\n');
console.log('brand/tokens/color.json');
