#!/usr/bin/env node
/**
 * Everything, from the parameters.
 *
 * `dist/` is output. Editing a file in it is a mistake the next build corrects
 * and gates/check-dist-clean.mjs reports.
 */
import { mkdirSync, writeFileSync, rmSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import {
  mark,
  type as typePiece,
  lockupSplit,
  lockupHorizontal,
  lockupStacked,
  boxedIcon,
  boxedLockup,
  STANDARD,
  SMALL,
  CAP,
} from './lockup.mjs';
import { toSvg, ico } from './svg.mjs';
import { businessCard, letterhead, markShape, lockupShapes, CMYK, PROOFED, pdf, eps, MM } from './print.mjs';
import { color } from './tokens.mjs';
import { brandCss, css, scss, js, dts, head, webmanifest } from './emit.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const DIST = join(root, 'dist');

const NAVY = color('color.brand.navy');
const PINK = color('color.brand.pink');
const WHITE = color('color.brand.white');

/** Ink options for a background-free asset. `currentColor` is the CSS one. */
const INKS = { navy: NAVY, pink: PINK, white: WHITE, current: 'currentColor' };

/**
 * Boxed variants. The name says mark-on-box; `type` is the colour the product
 * name takes, which sits on the page rather than on the box and therefore
 * cannot be the box's own ink. Every pair here is checked by
 * gates/check-contrast.mjs before it ships.
 */
const BOXES = {
  'white-on-navy': { ink: WHITE, surface: NAVY, type: NAVY },
  'white-on-pink': { ink: WHITE, surface: PINK, type: NAVY },
  'pink-on-navy': { ink: PINK, surface: NAVY, type: NAVY },
  reverse: { ink: NAVY, surface: WHITE, type: WHITE },
};

const write = (rel, data) => {
  const p = join(DIST, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, data);
  return rel;
};

const png = (svg, width, height) =>
  new Resvg(svg, { fitTo: height ? { mode: 'height', value: height } : { mode: 'width', value: width } })
    .render()
    .asPng();

/** A piece reduced to what an inline <svg> needs: a viewBox and a path. */
function pathData(piece) {
  const svg = toSvg(piece, { ink: 'currentColor', title: '' });
  const d = /<path d="([^"]+)"/.exec(svg)[1];
  const rule = /fill-rule="([^"]+)"/.exec(svg)?.[1] ?? 'nonzero';
  return { viewBox: /viewBox="([^"]+)"/.exec(svg)[1], d, fillRule: rule };
}

const NOTE = PROOFED
  ? 'CMYK builds confirmed against a printed proof.'
  : 'CMYK builds are NOT PROOFED. See print/README.md before ordering.';

function printNote() {
  return `# Print

Every file here is vector and DeviceCMYK, generated by \`src/print.mjs\`.

## Read this before ordering anything

${PROOFED ? 'The CMYK builds have been confirmed against a printed proof.' : `**The CMYK builds have not been proofed.** They are in
\`brand/tokens/print.json\`, seeded from a naive sRGB conversion, and the pink
is the one most likely to be wrong: \`#EF2F88\` is outside CMYK gamut and will
come back duller and warmer whatever the build. Send a proof, then replace the
values in that file and rebuild. Nothing else changes.`}

## What is here

| File | For |
| ---- | --- |
| \`<product>/mark-*.pdf\`, \`.eps\` | the mark alone, one colour |
| \`<product>/lockup-*.pdf\`, \`.eps\` | mark and name, one cap height apart |
| \`<product>/icon-reversed.*\` | the mark knocked out of a navy field |
| \`stationery/business-card.pdf\` | 85 x 55 mm, 3 mm bleed, TrimBox set |
| \`stationery/letterhead-a4.pdf\` | A4, 20 mm margin |

The stationery reads \`brand/stationery/card.json\`, whose values are
placeholders. They are deliberately unusable (\`example.invalid\`, \`REPLACE
NAME\`) so that one cannot reach paper by looking plausible.

Type is outlined, so no font is embedded and no RIP needs Montserrat. The text
is therefore not selectable, which on a card costs nothing.
`;
}

/**
 * An email signature is a table with inline styles, because a mail client will
 * strip a stylesheet, ignore a flex container and refuse an SVG.
 */
function signature() {
  return `<!-- Generated by src/build.mjs. Host signature-lockup@2x.png somewhere public
     and replace the src, or attach it and reference it as cid:wavingeye-logo. -->
<table cellpadding="0" cellspacing="0" border="0" style="font-family:Helvetica,Arial,sans-serif;color:${NAVY}">
  <tr>
    <td style="padding-right:16px;vertical-align:top">
      <img src="signature-lockup@2x.png" width="220" alt="WavingEye" style="display:block;border:0">
    </td>
    <td style="border-left:1px solid ${color('color.neutral.300')};padding-left:16px;font-size:13px;line-height:1.5">
      <div style="font-weight:600">REPLACE NAME</div>
      <div style="color:${color('color.neutral.700')}">REPLACE ROLE</div>
      <div style="padding-top:6px">
        <a href="mailto:replace@example.invalid" style="color:${color('color.brand.pinkOnLight')};text-decoration:none">replace@example.invalid</a>
      </div>
      <div style="color:${color('color.neutral.700')}">+00 000 0000000</div>
    </td>
  </tr>
</table>
`;
}

function forms(product) {
  const lines = product.split ?? [product.wordmark];
  return {
    mark: () => mark({}),
    'mark-small': () => mark({ cut: SMALL }),
    'mark-outline': () => mark({ style: 'outline' }),
    wordmark: () => typePiece(product.wordmark),
    'lockup-split': product.split ? () => lockupSplit(product.split[0], product.split[1]) : null,
    'lockup-horizontal': () => lockupHorizontal(product.wordmark),
    'lockup-stacked': () => lockupStacked(lines),
    'boxed-icon': () => boxedIcon({ fraction: 0.5 }),
    'boxed-lockup': () => boxedLockup(product.wordmark, { boxFraction: 0.5 }),
  };
}

/**
 * Padding is a per-target number, not a constant, because the platforms
 * disagree: an Android adaptive layer keeps only its inner 72 of 108 dp, a
 * maskable icon its inner 80%, and a favicon is not masked at all.
 */
const RASTER = {
  favicon: (p) => [
    { file: 'favicon-16.png', piece: mark({ cut: SMALL }), ink: NAVY, size: 16, fraction: 0.94 },
    { file: 'favicon-32.png', piece: mark({ cut: SMALL }), ink: NAVY, size: 32, fraction: 0.94 },
    { file: 'favicon-48.png', piece: mark({ cut: SMALL }), ink: NAVY, size: 48, fraction: 0.94 },
  ],
  'apple-touch': () => [
    { file: 'apple-touch-icon-180.png', piece: boxedIcon({ fraction: 0.62 }), box: 'white-on-navy', size: 180 },
  ],
  android: () => [
    { file: 'android-192.png', piece: boxedIcon({ fraction: 0.55 }), box: 'white-on-navy', size: 192 },
    { file: 'android-512.png', piece: boxedIcon({ fraction: 0.55 }), box: 'white-on-navy', size: 512 },
    { file: 'android-adaptive-foreground-432.png', piece: mark({}), ink: WHITE, size: 432, fraction: 0.44 },
  ],
  maskable: () => [
    { file: 'maskable-512.png', piece: boxedIcon({ fraction: 0.5 }), box: 'white-on-navy', size: 512 },
  ],
  'app-store': () => [
    { file: 'app-store-1024.png', piece: boxedIcon({ fraction: 0.62 }), box: 'white-on-navy', size: 1024 },
  ],
  og: (p) => [{ file: 'og-1200x630.png', og: true, size: 1200 }],
};

function ogCard(product) {
  const piece = lockupHorizontal(product.wordmark);
  const scale = 630 / 4 / piece.height;
  const w = piece.width * scale;
  const h = piece.height * scale;
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630">`,
    `<rect width="1200" height="630" fill="${NAVY}"/>`,
    `<g transform="translate(${(1200 - w) / 2} ${(630 - h) / 2}) scale(${scale})">${piece.body(WHITE)}</g>`,
    `</svg>`,
  ].join('');
}

function run() {
  rmSync(DIST, { recursive: true, force: true });
  const manifest = { generated: new Date().toISOString().slice(0, 10), assets: [] };
  const products = readdirSync(join(root, 'brand/products'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(join(root, 'brand/products', f), 'utf8')));

  for (const product of products) {
    const table = forms(product);
    for (const name of product.forms) {
      const make = table[name];
      if (!make) continue;
      const boxed = name.startsWith('boxed');
      const variants = boxed
        ? Object.entries(BOXES)
        : Object.entries(INKS).map(([suffix, ink]) => [suffix, { ink, surface: 'none' }]);
      for (const [suffix, colors] of variants) {
        const piece = make();
        const title = `${product.title} ${name.replace(/-/g, ' ')}`;
        const svg = toSvg(piece, { ...colors, title });
        const rel = write(`${product.name}/${name}-${suffix}.svg`, svg);
        manifest.assets.push({ product: product.name, form: name, variant: suffix, file: rel, type: 'image/svg+xml' });
      }
    }
    // The mark on its own, also as the small cut, both as outlines.
    for (const [suffix, ink] of Object.entries(INKS)) {
      const piece = mark({ cut: SMALL, style: 'outline' });
      write(`${product.name}/mark-small-outline-${suffix}.svg`, toSvg(piece, { ink, title: `${product.title} mark` }));
    }

    // The favicon that follows the reader's theme, which a PNG cannot do.
    const fav = mark({ cut: SMALL });
    write(
      `${product.name}/favicon.svg`,
      toSvg(fav, {
        ink: 'currentColor',
        title: `${product.title}`,
        style: `svg{color:${NAVY}}@media(prefers-color-scheme:dark){svg{color:${WHITE}}}`,
      }),
    );

    const icoParts = [];
    for (const target of product.targets) {
      for (const spec of RASTER[target](product)) {
        let svg;
        if (spec.og) svg = ogCard(product);
        else if (spec.box) svg = toSvg(spec.piece, { ...BOXES[spec.box], title: product.title });
        else {
          const pad = spec.fraction ? (spec.piece.width / spec.fraction - spec.piece.width) / 2 : 0;
          const square = spec.piece.width + pad * 2;
          svg = toSvg(
            { ...spec.piece, width: square, height: square, body: spec.piece.body },
            { ink: spec.ink, title: product.title },
          );
          // Re-centre inside the square canvas.
          svg = svg.replace(
            /(<title>.*?<\/title>)/,
            `$1<g transform="translate(${(square - spec.piece.width) / 2} ${(square - spec.piece.height) / 2})">`,
          );
          svg = svg.replace('</svg>', '</g></svg>');
        }
        const data = png(svg, spec.size, spec.og ? undefined : undefined);
        const rel = write(`${product.name}/${spec.file}`, data);
        manifest.assets.push({ product: product.name, target, file: rel, type: 'image/png' });
        if (spec.file.startsWith('favicon-')) icoParts.push({ size: spec.size, data });
      }
    }
    if (icoParts.length) write(`${product.name}/favicon.ico`, ico(icoParts));
    // The path data itself, for a consumer that inlines the mark rather than
    // linking it. An <img> cannot inherit currentColor; an inline <svg> can,
    // and that is the whole difference between a logo that follows a theme and
    // one that does not.
    write(
      `${product.name}/paths.json`,
      JSON.stringify(
        {
          mark: pathData(mark({})),
          markSmall: pathData(mark({ cut: SMALL })),
          markOutline: pathData(mark({ style: 'outline' })),
        },
        null,
        2,
      ),
    );
    const base = product.base ?? '/';
    write(`${product.name}/head.html`, head(product.name, base));
    write(`${product.name}/site.webmanifest`, webmanifest(product, { navy: NAVY }, base));
  }

  // Print. Vector, DeviceCMYK, laid out in millimetres, from the same paths.
  for (const product of products) {
    const inks = { navy: CMYK.navy, pink: CMYK.pink, black: CMYK.black };
    for (const [name, ink] of Object.entries(inks)) {
      const page = { width: 60 * MM, height: 60 * MM, shapes: [markShape(50, 5, 5, ink)] };
      write(`print/${product.name}/mark-${name}.pdf`, pdf([page], { title: `${product.title} mark`, note: NOTE }));
      write(`print/${product.name}/mark-${name}.eps`, eps(page, { title: `${product.title} mark` }));
      const lock = lockupShapes(product.wordmark, 6, 5, 5, ink);
      const lockPage = { width: (lock.width + 10) * MM, height: (lock.height + 10) * MM, shapes: lock.shapes };
      write(`print/${product.name}/lockup-${name}.pdf`, pdf([lockPage], { title: `${product.title} lockup`, note: NOTE }));
      write(`print/${product.name}/lockup-${name}.eps`, eps(lockPage, { title: `${product.title} lockup` }));
    }
    // Reversed: the mark knocked out of a navy field, for anything printed dark.
    const rev = {
      width: 60 * MM,
      height: 60 * MM,
      rects: [{ x: 0, y: 0, width: 60 * MM, height: 60 * MM, cmyk: CMYK.navy }],
      shapes: [markShape(30, 15, 15, CMYK.white)],
    };
    write(`print/${product.name}/icon-reversed.pdf`, pdf([rev], { title: `${product.title} reversed icon`, note: NOTE }));
    write(`print/${product.name}/icon-reversed.eps`, eps(rev, { title: `${product.title} reversed icon` }));
  }
  const cardPages = businessCard();
  write('print/stationery/business-card.pdf', pdf([cardPages.front, cardPages.back], { title: 'WavingEye business card', note: NOTE }));
  write('print/stationery/letterhead-a4.pdf', pdf([letterhead()], { title: 'WavingEye letterhead', note: NOTE }));
  write('print/README.md', printNote());

  // The email signature, which is the one place a PNG is the right answer:
  // no mail client can be relied on for SVG, and half of them strip <style>.
  const sigSvg = toSvg(lockupHorizontal('WAVING EYE'), { ink: NAVY, title: 'WavingEye' });
  write('email/signature-lockup@2x.png', png(sigSvg, 440));
  write('email/signature.html', signature());

  // What a project styles against, rather than what it has to look up.
  write('tokens/brand.css', brandCss());
  write('tokens/theme.css', css());
  write('tokens/color.scss', scss());
  write('tokens/color.js', js());
  write('tokens/color.d.ts', dts());
  // The contract a product's own theme answers to: the names, and the floor
  // each one clears. Values are the product's business.
  write('tokens/vocabulary.json', readFileSync(join(root, 'brand/tokens/vocabulary.json'), 'utf8'));
  manifest.tokens = {
    brand: 'tokens/brand.css',
    theme: 'tokens/theme.css',
    scss: 'tokens/color.scss',
    js: 'tokens/color.js',
    types: 'tokens/color.d.ts',
  };

  writeFileSync(join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2));
  console.log(`${manifest.assets.length} assets in dist/`);
}

run();
