/**
 * What a consuming project actually installs, in two layers that are not the
 * same kind of thing.
 *
 * `brand.css` is the identity: six values, no theme switching, mandatory. Every
 * product imports it and maps it into its own token names under whatever theme
 * strategy it already has.
 *
 * `theme.css` is a whole opinionated palette, surfaces and inks and neutrals,
 * for a project that has no theme of its own. It is optional and most products
 * with a designer will not want it. Hikaru's theme is warm off-white with a
 * blue accent, argued in its own token file; pushing a cool navy-hued ramp into
 * it would be the brand overwriting a product decision that is none of its
 * business. src/validate.mjs is what the brand asks of such a product instead.
 */
import { tokens, resolve } from './tokens.mjs';

const PREFIX = 'we';

/**
 * The roles a consumer styles against. Left value is light, right is dark.
 *
 * Every pair here is a decision from docs/decisions.md rather than a shade:
 * the logo turns white on dark because navy against neutral-950 is 1.15:1, and
 * accent text switches to pinkOnDark for the same reason in the other
 * direction. gates/check-theme-roles.mjs reads this table and puts every ink on
 * every surface it can land on, in both themes.
 */
export const ROLES = [
  ['surface', 'color.neutral.50', 'color.neutral.950'],
  ['surface-raised', 'color.brand.white', 'color.neutral.900'],
  ['surface-sunken', 'color.neutral.100', 'color.neutral.800'],
  ['surface-brand', 'color.brand.navy', 'color.brand.navy'],
  ['ink', 'color.brand.navy', 'color.neutral.100'],
  ['ink-muted', 'color.neutral.700', 'color.neutral.300'],
  ['ink-subtle', 'color.neutral.600', 'color.neutral.400'],
  ['ink-on-brand', 'color.brand.white', 'color.brand.white'],
  ['rule', 'color.neutral.300', 'color.neutral.700'],
  ['accent', 'color.brand.pink', 'color.brand.pink'],
  ['accent-text', 'color.brand.pinkOnLight', 'color.brand.pinkOnDark'],
  ['logo', 'color.brand.navy', 'color.brand.white'],
  ['success', 'color.accent.green.600', 'color.accent.green.400'],
  ['warning', 'color.accent.amber.600', 'color.accent.amber.400'],
  ['danger', 'color.accent.red.600', 'color.accent.red.400'],
  ['info', 'color.accent.blue.600', 'color.accent.blue.400'],
];

const scale = () =>
  Object.keys(tokens)
    .filter((k) => k.startsWith('color.') && typeof resolve(tokens[k]) === 'string' && resolve(tokens[k]).startsWith('#'))
    .map((k) => [k.slice('color.'.length).replace(/\./g, '-'), resolve(tokens[k])]);

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/**
 * Custom properties, in the three-state shape a theme actually has: an explicit
 * choice on the root element, an OS preference, and the far more common case of
 * neither, where only the media query separates them.
 */
/** The identity. Flat, because a product owns its own theme switching. */
export function brandCss() {
  const identity = ['pink', 'pinkOnLight', 'pinkOnDark', 'navy', 'white', 'black'];
  const lines = identity
    .map((k) => `  --${PREFIX}-brand-${kebab(k)}: ${resolve(tokens[`color.brand.${k}`])};`)
    .join('\n');
  return `/* Generated by src/emit.mjs. Do not edit. The identity, and nothing else. */
:root {
${lines}
}

/*
 * Map these into your own tokens under your own theme strategy. The one rule
 * the brand asks of you is that the mark can be seen wherever you render it,
 * which src/validate.mjs checks:
 *
 *   :root { --my-logo: var(--${PREFIX}-brand-navy); }
 *   .dark { --my-logo: var(--${PREFIX}-brand-white); }
 */
`;
}

export function css() {
  const raw = scale()
    .map(([name, hex]) => `  --${PREFIX}-${kebab(name)}: ${hex};`)
    .join('\n');
  const roles = (i, indent = '  ') =>
    ROLES.map(([name, light, dark]) => `${indent}--${PREFIX}-${name}: ${resolve(tokens[i ? dark : light])};`).join('\n');
  return `/* Generated by src/emit.mjs. Do not edit.
 *
 * A whole palette, for a project with no theme of its own. A product that has
 * one wants tokens/brand.css instead, and its own surfaces underneath.
 */
:root {
${raw}

${roles(0)}
}

/* The un-stamped default: no explicit choice, so only the OS separates them. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${roles(1, '    ')}
  }
}

/* An explicit choice wins in either direction. */
:root[data-theme='dark'] {
${roles(1)}
}
`;
}

export function scss() {
  return (
    '// Generated by src/emit.mjs. Do not edit.\n' +
    scale()
      .map(([name, hex]) => `$${PREFIX}-${kebab(name)}: ${hex};`)
      .join('\n') +
    '\n'
  );
}

export function js() {
  const raw = scale();
  const body = raw.map(([name, hex]) => `  ${camel(name)}: '${hex}',`).join('\n');
  const light = ROLES.map(([n, l]) => `    ${camel(n)}: '${resolve(tokens[l])}',`).join('\n');
  const dark = ROLES.map(([n, , d]) => `    ${camel(n)}: '${resolve(tokens[d])}',`).join('\n');
  return `// Generated by src/emit.mjs. Do not edit.
export const color = {
${body}
};

export const theme = {
  light: {
${light}
  },
  dark: {
${dark}
  },
};

export default { color, theme };
`;
}

export function dts() {
  const keys = scale().map(([n]) => `  readonly ${camel(n)}: string;`).join('\n');
  const roles = ROLES.map(([n]) => `  readonly ${camel(n)}: string;`).join('\n');
  return `// Generated by src/emit.mjs. Do not edit.
export declare const color: {
${keys}
};
export interface Theme {
${roles}
}
export declare const theme: { readonly light: Theme; readonly dark: Theme };
declare const _default: { color: typeof color; theme: typeof theme };
export default _default;
`;
}

/**
 * The four tags that cover every browser worth covering, and no more.
 *
 * `base` is where the consumer actually serves these. It defaults to the site
 * root and Hikaru serves them from `/brand/`, so the paths are a parameter
 * rather than an assumption somebody discovers is wrong from a 404.
 */
export function head(product, base = '/') {
  const at = (f) => `${base.replace(/\/$/, '')}/${f}`;
  return `<!-- Generated by src/emit.mjs. Serve dist/${product}/ at ${base}. -->
<link rel="icon" href="${at('favicon.ico')}" sizes="32x32">
<link rel="icon" href="${at('favicon.svg')}" type="image/svg+xml">
<link rel="apple-touch-icon" href="${at('apple-touch-icon-180.png')}">
<link rel="manifest" href="${at('site.webmanifest')}">
`;
}

export function webmanifest(product, colors, base = '/') {
  const at = (f) => `${base.replace(/\/$/, '')}/${f}`;
  return JSON.stringify(
    {
      name: product.title,
      short_name: product.title,
      icons: [
        { src: at('android-192.png'), sizes: '192x192', type: 'image/png' },
        { src: at('android-512.png'), sizes: '512x512', type: 'image/png' },
        { src: at('maskable-512.png'), sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
      theme_color: colors.navy,
      background_color: colors.navy,
      display: 'standalone',
    },
    null,
    2,
  );
}
